on:
  workflow_dispatch:
    inputs:
        releaseDescription:
          description: 'Provide a release description.'
          required: true
name: Deploy Azure resources
jobs:
  create-azure-resources:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3
      with:
        ref: dev

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./appDeployment/main.bicep
        parameters: ./appDeployment/devparameters.json
        failOnStdErr: false
