on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Provide the release environment'
          required: true
          type: environment

name: My App Deployment
jobs:
  setup-DEV-specific-parameters:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: ./.github/workflows/devParams.yml@main

  setup-UAT-specific-parameters:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: ./.github/workflows/uatParams.yml@main

  create-azure-resources:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3
      with:
        ref: dev

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: microsoft/variable-substitution@v1 
      with:
        files: './appDeployment/parameters.json'

      # Deploy Bicep file
    - name: deploy bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.resourceGroup }}
        template: ./appDeployment/main.bicep
        parameters: ./appDeployment/parameters.json
        failOnStdErr: false
