on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Provide the release environment'
          required: true
          type: environment

env:
  parameters.location.value: 'east us'
  parameters.storageAccountName.value: amstststg
  parameters.appInsightName.value: amststappinsight
  parameters.appServicePlanName.value: amstest-asp
  parameters.functionAppName.value: amststfuncapp
  parameters.keyVaultName.value: amststvault
  parameters.keyVaultSecretName.value: amstestsecret
  parameters.vnetName.value: amstestVnet
  parameters.subnetName.value: amstestSubnet
  parameters.keyVaultSecretValue.value: topsecretvalue
  parameters.tenantId.value: 3a6e195f-a33b-4031-a66a-0434183703d9
  parameters.environment.value: DEV
  parameters.resourceGroup.value: amsPune-DEV
  resourceGroup: amsPune-DEV

name: My awesome app deployment
jobs:
  create-azure-resources:
    environment: DEV
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3
      with:
        ref: dev

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: microsoft/variable-substitution@v1 
      with:
        files: './appDeployment/parameters.json'

      # Deploy Bicep file
    - name: deploy bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.resourceGroup }}
        template: ./appDeployment/main.bicep
        parameters: ./appDeployment/parameters.json
        failOnStdErr: false
